var elementorFrontendConfig = {
  environmentMode: {
    edit: false,
    wpPreview: false,
    isScriptDebug: false,
  },
  i18n: {

  },
  is_rtl: false,
  breakpoints: { xs: 0, sm: 480, md: 768, lg: 1025, xl: 1440, xxl: 1600 },
  responsive: {
    breakpoints: {
      mobile: {
        label: "Mobile",
        value: 767,
        default_value: 767,
        direction: "max",
        is_enabled: true,
      },
      mobile_extra: {
        label: "Mobile Extra",
        value: 880,
        default_value: 880,
        direction: "max",
        is_enabled: false,
      },
      tablet: {
        label: "Tablet",
        value: 1024,
        default_value: 1024,
        direction: "max",
        is_enabled: true,
      },
      tablet_extra: {
        label: "Tablet Extra",
        value: 1200,
        default_value: 1200,
        direction: "max",
        is_enabled: false,
      },
      laptop: {
        label: "Laptop",
        value: 1366,
        default_value: 1366,
        direction: "max",
        is_enabled: false,
      },
      widescreen: {
        label: "Widescreen",
        value: 2400,
        default_value: 2400,
        direction: "min",
        is_enabled: false,
      },
    },
  },
  version: "3.4.4",
  is_static: false,
  experimentalFeatures: {
    e_dom_optimization: true,
    a11y_improvements: true,
    e_import_export: true,
    additional_custom_breakpoints: true,
    "hello-theme-header-footer": true,
    "landing-pages": true,
    "elements-color-picker": true,
    "admin-top-bar": true,
    "form-submissions": true,
  },
  urls: {
    assets:
      "https:\/\/nobtheentertainer.tech\/wp-content\/plugins\/elementor\/assets\/",
  },
  settings: { page: [], editorPreferences: [] },
  kit: {
    active_breakpoints: ["viewport_mobile", "viewport_tablet"],
    global_image_lightbox: "yes",
    lightbox_enable_counter: "yes",
    lightbox_enable_fullscreen: "yes",
    lightbox_enable_zoom: "yes",
    lightbox_enable_share: "yes",
    lightbox_title_src: "title",
    lightbox_description_src: "description",
    hello_header_logo_type: "logo",
    hello_header_menu_layout: "horizontal",
    hello_footer_logo_type: "logo",
  },
  post: {
    id: 417,
    title: "",
    excerpt: "",
    featuredImage: false,
  },
};

var jetPopupData = {
    elements_data: { sections: [], columns: [], widgets: [] },
    version: "1.3.1",
    ajax_url: "",
  };

/* <![CDATA[ */
var JetTricksSettings = {
  elements_data: {
    sections: {
      2496501: {
        view_more: false,
        particles: "false",
        particles_json: "",
      },
      "1003c2d": {
        view_more: false,
        particles: "true",
        particles_json:
          '{\n  "particles": {\n    "number": {\n      "value": 110,\n      "density": {\n        "enable": true,\n        "value_area": 800\n      }\n    },\n    "color": {\n      "value": "#ffffff"\n    },\n    "shape": {\n      "type": "circle",\n      "stroke": {\n        "width": 0,\n        "color": "#00FF00"\n      },\n      "polygon": {\n        "nb_sides": 5\n      },\n      "image": {\n        "src": "img\/github.svg",\n        "width": 100,\n        "height": 100\n      }\n    },\n    "opacity": {\n      "value": 0.5,\n      "random": false,\n      "anim": {\n        "enable": false,\n        "speed": 1,\n        "opacity_min": 0.1,\n        "sync": false\n      }\n    },\n    "size": {\n      "value": 3,\n      "random": true,\n      "anim": {\n        "enable": false,\n        "speed": 40,\n        "size_min": 0.1,\n        "sync": false\n      }\n    },\n    "line_linked": {\n      "enable": true,\n      "distance": 150,\n      "color": "#ffffff",\n      "opacity": 0.4,\n      "width": 1\n    },\n    "move": {\n      "enable": true,\n      "speed": 6,\n      "direction": "none",\n      "random": false,\n      "straight": false,\n      "out_mode": "out",\n      "bounce": false,\n      "attract": {\n        "enable": false,\n        "rotateX": 600,\n        "rotateY": 1200\n      }\n    }\n  },\n  "interactivity": {\n    "detect_on": "canvas",\n    "events": {\n      "onhover": {\n        "enable": true,\n        "mode": "repulse"\n      },\n      "onclick": {\n        "enable": false,\n        "mode": "push"\n      },\n      "resize": true\n    },\n    "modes": {\n      "grab": {\n        "distance": 400,\n        "line_linked": {\n          "opacity": 1\n        }\n      },\n      "bubble": {\n        "distance": 400,\n        "size": 40,\n        "duration": 2,\n        "opacity": 8,\n        "speed": 3\n      },\n      "repulse": {\n        "distance": 200,\n        "duration": 0.4\n      },\n      "push": {\n        "particles_nb": 4\n      },\n      "remove": {\n        "particles_nb": 2\n      }\n    }\n  },\n  "retina_detect": true\n}',
      },
      a4c22fc: {
        view_more: false,
        particles: "false",
        particles_json: "",
      },
      "5f7887f": {
        view_more: false,
        particles: "false",
        particles_json: "",
      },
      "2cd114c": {
        view_more: false,
        particles: "false",
        particles_json: "",
      },
      "1a1a16b": {
        view_more: false,
        particles: "false",
        particles_json: "",
      },
      eba0c43: {
        view_more: false,
        particles: "true",
        particles_json:
          '{\n  "particles": {\n    "number": {\n      "value": 10,\n      "density": {\n        "enable": true,\n        "value_area": 800\n      }\n    },\n    "color": {\n      "value": "#5b6534"\n    },\n    "shape": {\n      "type": "polygon",\n      "stroke": {\n        "width": 0,\n        "color": "#00FF00"\n      },\n      "polygon": {\n        "nb_sides": 6\n      },\n      "image": {\n        "src": "img\/github.svg",\n        "width": 100,\n        "height": 100\n      }\n    },\n    "opacity": {\n      "value": 0.3,\n      "random": true,\n      "anim": {\n        "enable": false,\n        "speed": 1,\n        "opacity_min": 0.1,\n        "sync": false\n      }\n    },\n    "size": {\n      "value": 160,\n      "random": false,\n      "anim": {\n        "enable": true,\n        "speed": 10,\n        "size_min": 40,\n        "sync": false\n      }\n    },\n    "line_linked": {\n      "enable": false,\n      "distance": 200,\n      "color": "#ffffff",\n      "opacity": 1,\n      "width": 2\n    },\n    "move": {\n      "enable": true,\n      "speed": 8,\n      "direction": "none",\n      "random": false,\n      "straight": false,\n      "out_mode": "out",\n      "bounce": false,\n      "attract": {\n        "enable": false,\n        "rotateX": 600,\n        "rotateY": 1200\n      }\n    }\n  },\n  "interactivity": {\n    "detect_on": "canvas",\n    "events": {\n      "onhover": {\n        "enable": false,\n        "mode": "repulse"\n      },\n      "onclick": {\n        "enable": false,\n        "mode": "push"\n      },\n      "resize": true\n    },\n    "modes": {\n      "grab": {\n        "distance": 400,\n        "line_linked": {\n          "opacity": 1\n        }\n      },\n      "bubble": {\n        "distance": 400,\n        "size": 40,\n        "duration": 2,\n        "opacity": 8,\n        "speed": 3\n      },\n      "repulse": {\n        "distance": 200,\n        "duration": 0.4\n      },\n      "push": {\n        "particles_nb": 4\n      },\n      "remove": {\n        "particles_nb": 2\n      }\n    }\n  },\n  "retina_detect": true\n}',
      },
      b3192e6: {
        view_more: false,
        particles: "false",
        particles_json: "",
      },
      f606476: {
        view_more: false,
        particles: "false",
        particles_json: "",
      },
      "034f978": {
        view_more: false,
        particles: "false",
        particles_json: "",
      },
      "3021fb0": {
        view_more: false,
        particles: "false",
        particles_json: "",
      },
      bf11f94: {
        view_more: false,
        particles: "false",
        particles_json: "",
      },
      dc40064: {
        view_more: false,
        particles: "false",
        particles_json: "",
      },
      "5edf451f": {
        view_more: false,
        particles: "false",
        particles_json: "",
      },
      "72384ddd": {
        view_more: false,
        particles: "false",
        particles_json: "",
      },
      "7b9b939": {
        view_more: false,
        particles: "false",
        particles_json: "",
      },
      "82af9e1": {
        view_more: false,
        particles: "false",
        particles_json: "",
      },
      a1d7143: {
        view_more: false,
        particles: "false",
        particles_json: "",
      },
      "8fc1981": {
        view_more: false,
        particles: "false",
        particles_json: "",
      },
      dff72dc: {
        view_more: false,
        particles: "false",
        particles_json: "",
      },
    },
    columns: [],
    widgets: {
      "375a8cc": [],
      "9b2f732": [],
      ff0c743: [],
      "2ad91c8": [],
      "50b61f9": [],
      d2c7e25: [],
      a7bd67e: [],
      "288aa22": [],
      "2dfb9c5": [],
      "393019a": [],
      c33859c: [],
      "54d96ef": [],
      "9ea623a": [],
      d7eef2d: [],
      "0c5717c": [],
      a4623ac: [],
      "48c1960": [],
      f6e550e: [],
      "874ebfe": [],
      e83958e: [],
      "97f735f": [],
      "4fc5986": [],
      f8c4997: [],
      "7976a31": [],
      c71da48: [],
      "87c7a60": [],
      "5c8681e": [],
      d989235: [],
      "6063afd": [],
      "85bd25c": [],
      "90a2851": [],
      "4fd46d8": [],
      "37e56a2": [],
      "17975b9": [],
      e9e5475: [],
      "62006a1": [],
      8798059: [],
      b48f923: [],
      d2a7931: [],
      7662054: [],
      "2f04a89": [],
      "30c0a08": [],
      d70b58c: [],
      "8a4ce98": [],
      ff31c91: [],
      ff73a38: [],
      b735316: [],
      "8cd70d9": [],
      "57b2516": [],
      "78f2f48": [],
      f79940e: [],
      "60eb322": [],
      "5e6a126d": [],
      "98df837": [],
      fdc2f37: [],
      cc8a1fe: [],
      b2e28fa: [],
      "58bbf37": [],
      "04e7b3e": [],
      "3d69b77": [],
      "8911f0e": [],
      "6b00826": [],
      f93d7a5: [],
      "894e69b": [],
      "0e7f74f": [],
      bfb39d4: [],
      "5e9b93e": [],
      "99d7af7": [],
      "671ca5d": [],
    },
  },
};
  /* ]]> */
